version: '3'

services:
  dqfontend:
    container_name: container_fontend
    image: image_fontend
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - "8080:80"
    stdin_open: true
    tty: true
    environment:
    - CHOKIDAR_USEPOLLING="true"